# BOAZ 12기 1주차 과제 파이썬 기초 문법

- 원하는 함수가 기억이 안나면 [이곳](https://wikidocs.net/book/1)을 참고해주세요
- 자주 사용하는 함수는 기억하는 것이 좋지만 대부분 기억이 나지 않습니다
- 원하는 기능이 있는 함수를 구글링 하는 능력이 중요합니다
- 영어로 어떻게 검색해야 하는지 학습하는 것이 가장 좋습니다

#### 1. 자료형 문제
#### 1-1. Slice 기능을 이용해 'you need python'(모두 소문자로) 을 출력하세요. 

In [1]:
a = "Life is too short, You need Python"


In [2]:
a.lower()

'life is too short, you need python'

#### 1-2. 숫자와 나누는 수를 입력하면 나머지를 반환하는 함수 remainder를 작성하세요

In [3]:
def reminder (a,b):
    return a%b
    

In [4]:
reminder(5,3)

2

#### 1-2. 입력한 수의 평균을 반환하는 함수 mean을 작성하세요 (*args를 이용해보세요 !)

In [15]:
def mean (a, *args):
    sum=0
    cnt=0
    for i in args :
        sum +=i ;
        cnt +=1 ;
    return sum/cnt 
    

In [16]:
print(mean(1,2,3),mean(1,2,3,4,5,6,7,8), sep = "\n")

2.5
5.0


#### 1-3. for와 range를 사용해서 0부터 9까지 중 홀수인 1, 3, 5, 7, 9만 odd_nums에 저장하고 출력하는 코드를 짜보세요. 

In [18]:
odd_nums = []
for i in range (0,10):
    if i%2==1 :
        odd_nums.append(i)

print(odd_nums)

[1, 3, 5, 7, 9]


#### 1-4. 다음 리스트에서 생일만 리스트에 담는 함수 birth를 작성하세요

In [1]:
pin1 = " 930115-1234567"
pin2 = "990101- 2257262"
pin3 = "000327 - 1010209"
pin4 = "010101-2047219 "
pin5 = "9706091360217"
pin = [pin1, pin2, pin3, pin4, pin5]
print(pin)


[' 930115-1234567', '990101- 2257262', '000327 - 1010209', '010101-2047219 ', '9706091360217']


In [6]:
def birth (arr) :
    pin2=[]
    for i in arr:
        s=i.strip()
#         print(s[2:6])
        pin2.append(s[2:6])
    print(pin2)


In [7]:
birth(pin)

['0115', '0101', '0327', '0101', '0609']


#### 2. 함수 문제
#### 2-1.  if/ elif/ else문을 사용해서 2019년이 윤년인지 계산하는 코드를 짜보세요. 
- 윤년 계산법
    - 연도가 400으로 나누어 떨어지면 윤년입니다. 
    - 연도가 4로 나누어 떨어지면서 100으로 나누어 떨어지지 않으면 윤년입니다. 

In [56]:
year = 2019 

if (year%400==0):
    print('윤년입니다.')
elif year %4==0 and year %100 !=0 :
    print('윤년입니다.')
else : 
    print('평년입니다. ')

평년입니다. 


#### 2-2. 더하기, 빼기, 곱하기, 나누기 기능이 있는 클래스 Calculator를 작성하세요

In [ ]:
class Calculator():
    def __init__(self,a,b):
       
        self.a=a
        self.b=b

    def add(self):
        result =self.a+self.b
        return result
    def subtract(self):
        result =self.a-self.b
        return result
    def multiply(self):
        result =self.a*self.b
        return result
    def divide(self):
        result =self.a/self.b
        return result



In [ ]:
Cal = Calculator(13,7)
print(Cal.add(),Cal.subtract(),Cal.multiply(),Cal.divide(), sep = "\n")

#### 2-3. 가위바위보 게임 만들기
다음 요구사항에 맞는 가위바위보 게임을 만들어보세요. 

In [ ]:
# 사용자에게 '가위', '바위', '보'를 입력받으세요. 
import random 

s=['가위','바위','보']

# 리스트에 가위, 바위, 보를 저장합니다. 
while(1):
# 게임을 무한 반복합니다. 
    A= input('입력하시오 : ')
# 사용자에게는 입력을 받고, 
    B= random.choice(s)
# 컴퓨터는 랜덤하게 선택합니다. 
    if A =="끝":
# 만약 사용자가 '끝'을 입력하면,
        break;
# 반복을 종료합니다. 
    print('A는 :'+A)
    print('B는 :'+B)
# 둘의 선택을 print 해봅니다. 

    if A==B:
# 만약 둘이 같은 것을 내면 
        print('비겼어요!')
# '비겼어요!'를 출력합니다.
    elif A=='가위':
# 아니라면 사용자가 가위인지 판단합니다.
        if B=='바위':
# 사용자가 가위이면서 컴퓨터가 바위이면 
            print('졌어요!')
# '졌어요!'를 출력하고 
        else :
            print('이겼어요!')
# 그렇지 않으면 
# '이겼어요!'를 출력합니다. 
    elif A=='바위':
        if B=='가위':
            print('이겼어요!')
        else :
            print('졌어요!')
    else:
        if B=='바위':
            print('이겼어요!')
        else :
            print('졌어요!')
# 같은 원리로 사용자가 바위일 때와

# 보일 때를 짜보세요. 

입력하시오 : 가위
A는 :가위
B는 :보
이겼어요!


# Numpy 연습문제

#### 1. Matrix 연산
#### 1-1. 다음과 같은 matrix a, b를 생성하고 서로 곱해보세요

In [95]:

a = np.arange(12).reshape((3,4))
a=a+1

b= np.array([[1,2,3],[5,6,7],[9,10,11],[1,2,3]])


In [97]:
print(a,b, sep ="\n")
print(a.dot(b))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [ 1  2  3]]
[[ 42  52  62]
 [106 132 158]
 [170 212 254]]


#### 1-2. 다음 두 벡터의 내적과 외적 값을 구하세요

In [5]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [6]:
import itertools
sum=0
for i in a*b : 
    sum+=i
print('내적 :'+ str(sum))


print('외적 :')
x=np.transpose([np.tile(a, len(b))*np.repeat(b, len(a))])
print(x.reshape(5,5))

내적 :130
외적 :
[[ 6 12 18 24 30]
 [ 7 14 21 28 35]
 [ 8 16 24 32 40]
 [ 9 18 27 36 45]
 [10 20 30 40 50]]


# Pandas

#### 1. dataframe 다루기
#### 1-1. 다음과 같은 dataframe을 생성하세요

In [7]:
# Your Code Here
import pandas as pd
twelve = pd.DataFrame(data={"조":['A','A','A','A','A','A','B','B','B','B','B','B',
                                'C','C','C','C','C','D','D','D','D','D','E','E','E','E','E'], 
                            "이름":['전승우','유응규','박재언','신광욱','박현정','문현주','성민석','이형남',
                                 '전은정','김아영','남궁찬','고동희','박서호','지현이','윤훈상','양광민',
                                 '송원호','양태일','하진용','정해원','유승룡','전용진','신하은','조문기','장현정','최준명','이동건'], "성별":[1,1,1,1,2,2,1,1,2,2,1,1,1,2,1,1,1,1,1,2,1,1,2,1,2,1,1]},
                     columns=['조','이름','성별'])



In [8]:
twelve

조   이름  성별
0   A  전승우   1
1   A  유응규   1
2   A  박재언   1
3   A  신광욱   1
4   A  박현정   2
5   A  문현주   2
6   B  성민석   1
7   B  이형남   1
8   B  전은정   2
9   B  김아영   2
10  B  남궁찬   1
11  B  고동희   1
12  C  박서호   1
13  C  지현이   2
14  C  윤훈상   1
15  C  양광민   1
16  C  송원호   1
17  D  양태일   1
18  D  하진용   1
19  D  정해원   2
20  D  유승룡   1
21  D  전용진   1
22  E  신하은   2
23  E  조문기   1
24  E  장현정   2
25  E  최준명   1
26  E  이동건   1

#### 1-2. A조 남자와 E조 여자를 출력하세요

In [16]:
twelve[(twelve['조']=='A') & (twelve['성별']==1)
      | (twelve['조']=='E') & (twelve['성별']==2)]


조   이름  성별
0   A  전승우   1
1   A  유응규   1
2   A  박재언   1
3   A  신광욱   1
22  E  신하은   2
24  E  장현정   2

#### 1-3. 이씨를 출력하세요 (List 내포 for문을 써서 한줄로 짜보세요 !)

In [3]:

result=[ i for i in twelve['이름'] if i[0]=='이']

In [4]:
result 

['이형남', '이동건']