
### Autograd: 자동 미분

### Autograd Package

Autograd 패키지는 tensor의 모든 연산에 자동 미분을 제공합니다. 이는 define-by-run의 프레임워크로 코드를 어떻게 작성하느냐에 따라 역전파가 정의된다는 뜻입니다. 역전파는 학습과정의 매 단계마다 달라집니다.

In [6]:
import torch
x = torch.ones(2,2,requires_grad=True) #tensor를 생성하고 requires_grad=True로 연산을 기록합니다.
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y = x+2 #gradient function이 자동으로 포함됩니다.
print(y)

z = y*y*3
out = z.mean()
print(z,out)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


### Gradient

In [8]:

print(out) # out = 3(x+2)*2
out.backward()

print(x)
print(x.grad) # d(out)/dx 를 출력합니다.

tensor(27., grad_fn=<MeanBackward1>)
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
x = torch.randn(3,requires_grad=True)

y=x*2

while y.data.norm() < 1000:
    
    #data.norm()은 점들 사이의 유클리디안 거리를 나타냅니다
    #torch.sqrt(torch.sum(torch.pow(y, 2)))
    
    y = y*2
    
    print(y,y.data.norm())

tensor([-6.3251,  3.3126,  1.5409], grad_fn=<MulBackward0>) tensor(7.3045)
tensor([-12.6503,   6.6253,   3.0818], grad_fn=<MulBackward0>) tensor(14.6090)
tensor([-25.3006,  13.2505,   6.1637], grad_fn=<MulBackward0>) tensor(29.2179)
tensor([-50.6012,  26.5010,  12.3274], grad_fn=<MulBackward0>) tensor(58.4358)
tensor([-101.2023,   53.0021,   24.6547], grad_fn=<MulBackward0>) tensor(116.8717)
tensor([-202.4046,  106.0042,   49.3094], grad_fn=<MulBackward0>) tensor(233.7433)
tensor([-404.8093,  212.0083,   98.6189], grad_fn=<MulBackward0>) tensor(467.4867)
tensor([-809.6186,  424.0167,  197.2377], grad_fn=<MulBackward0>) tensor(934.9733)
tensor([-1619.2372,   848.0333,   394.4754], grad_fn=<MulBackward0>) tensor(1869.9467)


In [10]:
gradients = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
print(y)
y.backward(gradients)
print(x.grad) # d(y)/d(x) 를 출력합니다

tensor([-1619.2372,   848.0333,   394.4754], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


### 1주차 과제 ))   MNIST 정확도 92% 이상 만들어보기


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim 

from torch.autograd import Variable 
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets

batch_size=32
learning_rate=0.01
num_epochs=5

train_dataset=datasets.MNIST(root='./data',train =True, 
                             transform = transforms.ToTensor(), download=True)
test_dataset=datasets.MNIST(root='./data',train =False, 
                             transform = transforms.ToTensor(), download=True)

train_loader=DataLoader(train_dataset,batch_size=batch_size,shuffle = True)
test_loader=DataLoader(test_dataset,batch_size=batch_size,shuffle = False)

Processing...
Done!


In [4]:
class NeuralNetwork(nn.Module):
    def __init__(self,num_classes=10):
        super(NeuralNetwork,self).__init__()
        self.layer1=nn.Linear(28*28,100)
        self.layer2=nn.Linear(100,200)
        self.layer3=nn.Linear(200,num_classes)
        
        def forward(self,x):
            out=x.view(x.size(0),-1)
            out=self.layer1(out)
            out=self.layer2(out)
            out=self.layer3(out)
            return out
#MODEL
model=NeuralNetwork()
#LOSS
criterion = nn.CrossEntropyLoss()
#OPTIMIZER
optimiizer = optim.SGD(model.parameters(),lr=learning_rate)
        

In [5]:
#학습시켜주기
for epoch in range(num_epochs):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-5-fb4e2086b479>, line 3)