### Pytorch
    Define-by-Run
### Pytorch Packages
    torch
    torch.autograd
    torch.nn
    torch.optim
    torch.multiprocessing
    torch.utils
    torch.legact
### Pytorch Tensor Basic Usage
    Create Tensor
    Indexing, Joining, Slicing
    Initialization
    Math Operations
### 1. Create Tensor

In [1]:
import torch
# torch.rand(size)
# 0~1 사이의 연속균등분포에서 값을 뽑아 5x3 텐서를 생성합니다. ~U(0,1)
x = torch.rand(2,3)
x

tensor([[0.9043, 0.3494, 0.0692],
        [0.9931, 0.1283, 0.7123]])

In [2]:
# torch.randn(size)
# randn의 경우 평균은 0, 표준편차는 1인 정규분포에서 값을 가져옵니다. ~z(0,1)
x1=torch.rand(3,4)
x2=torch.rand(4,5)
torch.mm(x1,x2)


tensor([[1.8794, 1.3950, 2.4325, 1.7419, 1.5864],
        [1.1483, 0.4369, 1.2853, 1.1647, 0.9593],
        [1.5752, 0.9025, 1.6632, 1.2300, 1.2428]])

In [3]:
# torch.randperm(n)
# 0부터 n-1까지 1씩 늘어나며 값을 랜덤으로 정렬합니다.
x = torch.randperm(5)
x

tensor([0, 1, 3, 2, 4])

In [4]:

#배치끼리의 행렬곱 = bmm
# torch.bmm(batch_matrix1, batch_matrix2)

x1=torch.rand(10,3,4)
x2=torch.rand(10,4,5)

torch.bmm(x1,x2).size()


torch.Size([10, 3, 5])

### 2) empty , zeros, ones, arrage, max

In [4]:
# torch.empty(size)
# 원하는 크기의 빈 텐서를 생성합니다.
x = torch.empty(2,3)
x

tensor([[0.0000e+00, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])

In [5]:
# torch.zeros(size)
# 원하는 크기의 빈 텐서를 생성합니다.
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# torch.ones(size)
# 원하는 크기의 1의 값을 가진 텐서를 생성합니다.
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# torch.arange(start,end,step=1)
# start값부터 end값 전까지 step만큼 더하며 텐서를 생성합니다.
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

In [8]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# tensor의 최대값을 산출합니다.

x = torch.rand(2,3)
print(x)

# 최대값을 출력합니다.
print(torch.max(x))

# 해당 차원에서 최대값과 그 위치를 출력합니다.
print(torch.max(x,1))

# 위치를 출력합니다.
print(torch.max(x,1)[1])

tensor([[0.4939, 0.4313, 0.7660],
        [0.5534, 0.2581, 0.5523]])
tensor(0.7660)
(tensor([0.7660, 0.5534]), tensor([2, 0]))
tensor([2, 0])


### 3) Tensor Data Type

In [9]:
# torch.empty(size, dtype=)
# torch.zeros(size, dtype=)
# torch.arange(start,end,dtype=)

# torch에서 지원하는 다양한 data type을 옵션으로 지정할 수 있습니다.

x = torch.empty(2,3, dtype=torch.float)
y = torch.zeros(2,3, dtype = torch.long)
z = torch.arange(0,3,step=0.5,dtype=torch.double)

print(x)
print(y)
print(z)


tensor([[-4.5080e+06,  4.5911e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [10]:
# torch.tensor(size or list, dtype = torch.floattensor) 
# 원하는 텐서를 바로 생성합니다.
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [11]:

# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
print(x)
x = torch.FloatTensor([2,3])
print(x)

tensor([[-4.5080e+06,  4.5911e-41,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00]])
tensor([2., 3.])


In [12]:

# tensor.type_as(tensor_type)
# tensor 형 변환
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### Tensor Size

In [13]:

# tensor.size()

x = torch.FloatTensor(10,12,3,3)

print(x.size()[:])
print(x.size()[0])

torch.Size([10, 12, 3, 3])
10


In [14]:
x = x.new_ones(5,3, dtype=torch.double) #5,3 차원의 새로운 텐서를 생성합니다.
print(x)

x = torch.randn_like(x,dtype=torch.float) # 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1433, -0.1459,  0.5400],
        [-1.2741, -0.4259, -0.8103],
        [-0.4838,  0.9952, -0.5255],
        [ 0.9416, -1.2798,  0.9148],
        [ 0.6058,  0.2276,  0.8081]])


### 2. Math Operation

In [15]:
# torch.add()
# 텐서의 값끼리 더합니다.

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1, x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [16]:
#차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.

x = torch.rand(1,5,3)
y = torch.rand(5,3)
torch.add(x,y)

tensor([[[1.0562, 0.9970, 0.6525],
         [1.5222, 0.7321, 0.4887],
         [0.4234, 1.0605, 0.6019],
         [1.5088, 0.6406, 0.9157],
         [0.0957, 1.1867, 0.7103]]])

In [17]:
# torch.pow(input,exponent)

x1 = torch.rand(3,4)

print(x1)
print(torch.pow(x1,2),"\n",x1**2)

tensor([[0.9797, 0.6905, 0.5697, 0.3001],
        [0.4197, 0.8841, 0.9708, 0.2957],
        [0.9136, 0.3232, 0.2683, 0.8903]])
tensor([[0.9599, 0.4768, 0.3246, 0.0900],
        [0.1762, 0.7817, 0.9424, 0.0874],
        [0.8347, 0.1045, 0.0720, 0.7926]]) 
 tensor([[0.9599, 0.4768, 0.3246, 0.0900],
        [0.1762, 0.7817, 0.9424, 0.0874],
        [0.8347, 0.1045, 0.0720, 0.7926]])


In [18]:
# torch.exp(tensor,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.exp(x1))

tensor([[0.9942, 0.2482, 0.3665, 0.9514],
        [0.8012, 0.4907, 0.0162, 0.7903],
        [0.1299, 0.6123, 0.2205, 0.1643]])
tensor([[2.7025, 1.2817, 1.4427, 2.5894],
        [2.2282, 1.6334, 1.0163, 2.2042],
        [1.1387, 1.8447, 1.2468, 1.1786]])


In [19]:
# torch.log(input,out=None)

x1 = torch.rand(3,4)

print(x1)
print(torch.log(x1))

tensor([[0.6287, 0.3815, 0.7263, 0.6222],
        [0.5106, 0.5622, 0.8236, 0.4261],
        [0.7156, 0.4511, 0.5921, 0.2744]])
tensor([[-0.4642, -0.9636, -0.3198, -0.4746],
        [-0.6721, -0.5758, -0.1941, -0.8531],
        [-0.3347, -0.7960, -0.5240, -1.2931]])


In [20]:

# torch.mm(matrix1, matrix2)

x1 = torch.rand(3,4)
x2 = torch.rand(4,5)

torch.mm(x1,x2)

tensor([[0.4853, 0.4143, 0.2360, 0.4805, 0.7299],
        [0.1824, 0.1489, 0.0255, 0.1774, 0.0389],
        [0.5269, 0.2769, 0.1885, 0.3560, 0.9062]])

In [21]:
# torch.bmm(batch_matrix1, batch_matrix2)

x1 = torch.rand(10,3,4)
x2 = torch.rand(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [22]:
# torch.dot(tensor1, tensor2)

torch.dot(torch.tensor([2,3]), torch.tensor([2,1]))

tensor(7)

In [23]:
# torch.t(matrix)
# tranpose

x1 = torch.rand(3,4)
print(x1.size(), x1.t().size())

# torch.transpose(input,dim0,dim1)

x1 = torch.rand(10,3,4)
x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

torch.Size([3, 4]) torch.Size([4, 3])


(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [24]:
#viw()  = 맨마지막에 일자로 만들어준다.


x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # -1의 경우 다른 차원들로 유추합니다. 이 경우에는 2로 유추합니다.
print(x.size())
print(y.size(),y)
print(z.size(),z)




torch.Size([4, 4])
torch.Size([16]) tensor([ 0.2608, -0.0604,  0.6726, -2.3146, -0.8927, -0.9933, -1.1368, -0.5905,
        -1.5724,  0.0433,  1.4543, -0.5445, -1.3004,  0.3925, -0.2250, -0.2531])
torch.Size([2, 8]) tensor([[ 0.2608, -0.0604,  0.6726, -2.3146, -0.8927, -0.9933, -1.1368, -0.5905],
        [-1.5724,  0.0433,  1.4543, -0.5445, -1.3004,  0.3925, -0.2250, -0.2531]])


### Indexing, Slicing, Joining

In [25]:
# Indexing
# tensor.index_select(input,dim,index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))
# index는 꼭 Longtensor로 입력해야 합니다.

print(x, "\n", out)

tensor([[0.7734, 0.5874, 0.1098],
        [0.4298, 0.6976, 0.5652],
        [0.9444, 0.4052, 0.8905],
        [0.4092, 0.8520, 0.0903]]) 
 tensor([[0.7734, 0.5874, 0.1098],
        [0.4092, 0.8520, 0.0903]])


In [26]:
# Joining
# torch.cat(seq, dim=0)
# dim을 기준으로 tensor를 합칩니다.
# dim = 0은 행, dim = 1은 열 기준입니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)
z2 = torch.cat([x,y],dim = 1)

print(x)
print(y)
print(z1)
print(z2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


In [29]:
# Slicing
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk 단위로 쪼갭니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print(x_1)
print(x_2)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [32]:
# Squeezing

# torch.squeez(input, dim=None)
# 1짜리 차원을 줄입니다.

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(), x2.size()




(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))